Rubric_Items = {
    'MiniExam_A': [ # this one might have been a little easy
        "-25:: Q1. Blank",
        "-15:: Q1. AA: Zonkos; CA; Honeydukes",
        "2:: Q1. Good production table",
        "7:: Q1. Good op. cost table",
        "-25:: Q2. Blank",
        "-15:: Q2. The PPF should go between 200 F and 100 M, with the point at (100, 100) being unatainable outside the PPF.",
        "-12:: Q2. The production level in question is a point at (100, 100), which is outside the PPF.",
        "5:: Q2. Good PPF setup.",
        "-8:: Q2. The PPF is correct but there's limited justification for the production point.",
        "-25:: Q3. Blank",
        "-15:: Q3. The PPF should pivot out from the original PPF on the M axis.",
        "-10:: Q3. The PPF should pivot out from the original PPF. It looks like your graph pivots from a different PPF.",
        "-8:: Q3. The PPF should pivot instead of shifting on both axes.",
        "-25:: Q4. Blank.",
        "-10:: Q4. The op cost table is different than what you wrote.",
        "-10:: Q4. The trade should be 1 M for anything betwen 3/3 F and 4/3 F. 1 M for 7/6 M would work.",
        "-5:: Q4. It looks like your calculations were off. But the rest follows.",
        "-1:: Q4. The PPF in Q3 throws off the numbers here, so the op cost table isn't correct but it follows."
    ],
    'MiniExam_B': [ # this one was way too hard
        "-25:: Q1. Blank",
        "-8:: Q1. The approach needs some work, ($80,200)",
        "-3:: Q1. Good approach with some math errors, ($80,200)",
        "-5:: Q1. Welfare is incorrect/incomplete",

        "-20:: Q2. Blank",
        "-9:: Q2. Incorrect shift",
        "-7:: Q2. Incorrect shift but the description follows",
        "-4:: Q2. Correct shift but some conclusions are missing",
        "-2:: Q2. Correct with some small issues",

        "-20:: Q3. Blank",
        "-9:: Q3. Incorrect shift",
        "-7:: Q3. Incorrect shift but the description follows",
        "-4:: Q3. Correct shift but some conclusions are incomplete/incorrect",
        "-2:: Q3. Correct with some small issues",

        "-35:: Q4. Blank",
        "-5:: Q4. The policy should be a price ceiling",
        "-3:: Q4. There should be a shortage after the policy",
        "-4:: Q4. The DWL isn't graphed correctly",
        "-1:: Q4. Some math errors in calculating DWL",
        "-3:: Q4. The surplus transfer isn't graphed correctly",
        "-1:: Q4. Some math errors in calculating the surplus transfer",
        "-4:: Q4. Good setup but missing/incomplete discussion",
    ],
    'MiniExam_C': [ # this one might have been a little easy
        '-5:: Incorrect market setup',
        '-5:: Incorrect externalities setup',
        '-10:: Missing equilibrium values',
        '-5:: Incorrect equilibrium values: (100/3, 100/3)',
        '-5:: Incorrect socially efficient quantity (30)',
        '-5:: Incorrect DWL',
        '-10:: Missing policy',
        '-5:: Incorrect policy',
        '-5:: Incorrect policy outcomes (p_b, p_s) = (40, 30)',
        '-5:: Incorrect government revenue: 300',
        '-5:: Missing incidence',
        '-2:: Some math errors',
        '-2:: Missing some minor calculations',
        '-8:: Q2. Correct answer is C',
        '-100:: Missing Submission',
    ],
    'MiniExam_D1': [
        '-5:: Q1a. Incorrect but good boxing method!',
        '-10:: Q1a. Incorrect: BR = {C if D, D if C}',
        '-5:: Q1b. Good definition but there is no dominant strategy: what Ron should do depends on what Harry does.',
        '-10:: Q1b. There is no dominant strategy: what Ron should do depends on what Harry does.',
        '-5:: Q1c. Incorrect but good boxing method! There are two (D,C) and (C,D).',
        '-10:: Q1c. Incorrect. There are two (D,C) and (C,D).',
        '-5:: Q1d. This is a free rider problem.',
        '-5:: Q2a. It is socially efficient since MSC = 1000 and MSB = 1200',
        '-10:: Q2a. MSC = 1000 and MSB = 1200, so it is socially efficient.',
        '-5:: Q2b. The vote would pass 300 to 100, with Gryffindor voting against.',
        '-10:: Q2b. The vote would pass 300 to 100.',
        '-5:: Q2c. No price will work. It would need to be greater than 2.5, but at that price only 300 students would go.',
        
        '-100:: Missing submission?', 
    ],
    'MiniExam_E': [
        '-8:: Q1a. Incorrect',
        '-3:: Q1a. Incorrect number but good process',
        '-8:: Q1b. Incorrect',
        '-3:: Q1b. Incorrect number but good process',
        '-8:: Q1c. Incorrect',
        '-3:: Q1c. Incorrect number but good process',
        '-8:: Q1d. Incorrect',
        '-3:: Q1d. Incorrect number but good process',
        '-12:: Q2a. Blank',
        '-8:: Q2a. Incorrect',
        '-3:: Q2a. Incorrect number but good process',
        '-12:: Q2b. Blank',
        '-8:: Q2b. Incorrect',
        '-3:: Q2b. Incorrect number but good process',
        '-12:: Q2c. Blank',
        '-8:: Q2c. Incorrect',
        '-3:: Q2c. Incorrect number but good process',
        '-100:: No submission. Let me know if I just missed it.',
    ],
    'MiniExam_F': [
        '-12:: Q1. Incorrect vertical intercept',
        '-12:: Q1. Incorrect horizontal intercept',
        '-12:: Q2. Incorrect direction of shift',
        '-12:: Q2. Incorrect intercept shifted',
        '-12:: Q2. Incorrect explanation',
        '-16:: Q2. No explanation given',
        '-8:: Q2. Incomplete explanation',
        '-12:: Q3. Substitution and income effects should increase C graphically',
        '-16:: Q3. No explanation given',
        '-8:: Q3. Incomplete explanation',
        '-12:: Q4. The budget should shift out',
        '-12:: Q4. Both incercepts should shift',
        '-12:: Q4. The solution to the consumers problem isnt correct',
        '-12:: Q4. The solution to the consumers problem is missing',
        '-8:: Q4. The conclusions and the graph dont match',
        '-16:: Q4. No explanation given',
        '-40:: Q4. Missing.',
        '-100:: No submission.',
    ],
}